// Generated by CoffeeScript 1.9.1
var AlterControllerExtensionService, app;

app = require('../../app');

AlterControllerExtensionService = (function() {
  function AlterControllerExtensionService(alter, first) {
    this.alter = alter;
    this.first = first;
  }

  AlterControllerExtensionService.prototype.bootstrap = function(ctrl, resourceName) {
    ctrl.save = (function(_this) {
      return function() {
        if (ctrl.beforeSave) {
          ctrl.beforeSave();
        }
        return _this.alter.persist(resourceName, ctrl[resourceName]);
      };
    })(this);
    ctrl.remove = (function(_this) {
      return function() {
        return _this.alter.remove(resourceName, ctrl[resourceName]);
      };
    })(this);
    return this.first.load(resourceName).then(function(val) {
      ctrl[resourceName] = val;
      return val;
    });
  };

  return AlterControllerExtensionService;

})();

AlterControllerExtensionService.$inject = ['AlterPersistenceService', 'FirstDocumentLoaderService'];

app.service('AlterControllerExtensionService', AlterControllerExtensionService);
