// Generated by CoffeeScript 1.9.1
var FirstDocumentLoaderService, app;

app = require('../../app');

FirstDocumentLoaderService = (function() {
  function FirstDocumentLoaderService(rest, route, $q) {
    this.rest = rest;
    this.route = route;
    this.$q = $q;
  }

  FirstDocumentLoaderService.prototype.load = function(resourceName) {
    if (this.route.id) {
      return this.rest.one(resourceName, this.route.id).get();
    } else {
      return this.$q(function(r) {
        return r({});
      });
    }
  };

  return FirstDocumentLoaderService;

})();

FirstDocumentLoaderService.$inject = ["Restangular", "$routeParams", "$q"];

app.service('FirstDocumentLoaderService', FirstDocumentLoaderService);
