// Generated by CoffeeScript 1.9.1
var TokenizerService, app;

app = require('../../app');

TokenizerService = (function() {
  function TokenizerService() {}

  TokenizerService.prototype.tokenize = function(str) {
    if (str === void 0) {
      return [];
    }
    if (str instanceof Array === true) {
      return str;
    }
    return _.compact(str.split(/[\s,|]/));
  };

  return TokenizerService;

})();

app.service('TokenizerService', TokenizerService);
