// Generated by CoffeeScript 1.9.1
var ErrorPool, ExperimentController, Inject, Q, _, annotate, ref,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ErrorPool = require('../config/error-codes').ErrorPool;

ref = require('di'), annotate = ref.annotate, Inject = ref.Inject;

_ = require('lodash');

Q = require('q');

ExperimentController = (function() {
  function ExperimentController(redis) {
    this.redis = redis;
    this.$one = bind(this.$one, this);
    this.$list = bind(this.$list, this);
    this.actions = {
      actionMap: {
        $one: [
          'get', function() {
            return "/experiment/:key";
          }
        ],
        $list: [
          'get', function() {
            return "/experiments";
          }
        ]
      },
      $one: this.$one,
      $list: this.$list
    };
  }

  ExperimentController.prototype.$list = function(req, res) {
    return this.redis.conn.keys('*').then(function(val) {
      return val;
    });
  };

  ExperimentController.prototype.$one = function(req, res) {
    var key;
    key = req.params.key;
    return this.redis.conn.get(key).then(function(count) {
      return {
        count: count
      };
    });
  };

  return ExperimentController;

})();

annotate(ExperimentController, new Inject(require('../connections/RedisConnection')));

module.exports = ExperimentController;
