// Generated by CoffeeScript 1.9.1
var BaseController, Dispatcher, Inject, ProgramController, annotate, ref,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ref = require('di'), Inject = ref.Inject, annotate = ref.annotate;

BaseController = require('./BaseController');

Dispatcher = require('../modules/Dispatcher');

ProgramController = (function() {
  function ProgramController(actions, dispatch) {
    this.actions = actions;
    this.dispatch = dispatch;
    this.postUpdateHook = bind(this.postUpdateHook, this);
    this.actions.resourceName = 'Program';
    this.actions.postUpdateHook = this.postUpdateHook;
  }

  ProgramController.prototype.postUpdateHook = function(program) {
    return this.dispatch.programUpdated(program._id).then(function() {
      return program;
    });
  };

  return ProgramController;

})();

annotate(ProgramController, new Inject(BaseController, Dispatcher));

module.exports = ProgramController;
