// Generated by CoffeeScript 1.9.1
var BaseController, Dispatcher, Inject, StyleController, annotate, ref,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ref = require('di'), Inject = ref.Inject, annotate = ref.annotate;

BaseController = require('./BaseController');

Dispatcher = require('../modules/Dispatcher');

StyleController = (function() {
  function StyleController(actions, dispatch) {
    this.actions = actions;
    this.dispatch = dispatch;
    this.postUpdateHook = bind(this.postUpdateHook, this);
    this.actions.$create = null;
    this.actions.resourceName = 'Style';
    this.actions.hasListOwner = false;
    this.actions.postUpdateHook = this.postUpdateHook;
  }

  StyleController.prototype.postUpdateHook = function(style) {
    return this.dispatch.styleUpdated(style._id).then(function() {
      return style;
    });
  };

  return StyleController;

})();

annotate(StyleController, new Inject(BaseController, Dispatcher));

module.exports = StyleController;
