// Generated by CoffeeScript 1.9.1
var KeywordCtrl, app;

app = require('../../app');

KeywordCtrl = (function() {
  function KeywordCtrl(rest) {
    rest.all('keywords').getList().then((function(_this) {
      return function(keywords) {
        _this.keywords = keywords;
      };
    })(this));
  }

  return KeywordCtrl;

})();

KeywordCtrl.$inject = ['Restangular'];

app.controller('KeywordListCtrl', KeywordCtrl);
