// Generated by CoffeeScript 1.9.1
var Inject, RedisConnection, config;

config = require('../config/config');

Inject = require('di').Inject;

RedisConnection = (function() {
  function RedisConnection(redisP) {
    this.conn = redisP.redis().createClient(config.redis.uri);
    this.conn.on('ready', function() {
      return bragi.log('application:redis', bragi.util.symbols.success, 'Redis Connection established successfully');
    });
    this.conn.on('error', function() {
      return bragi.log('application:redis', bragi.util.symbols.error, 'Redis Connection could not be established');
    });
  }

  return RedisConnection;

})();

RedisConnection.annotations = [new Inject(require('../providers/RedisProvider'))];

module.exports = RedisConnection;
