// Generated by CoffeeScript 1.9.1
'use strict';
var _, config, env, fs, path, userconfig;

fs = require('fs');

path = require('path');

_ = require('lodash');

env = process.env.NODE_ENV || 'development';

config = _.merge(require('./env/all'), require('./env/' + env || {}));

if (process.env.USER && env !== 'production') {
  userconfig = './user/' + process.env.USER + '.js';
  if (fs.existsSync(path.join(path.join(__dirname, userconfig)))) {
    config = _.merge(config, require(userconfig));
  } else {
    console.log('User config not found, defaulting to development.js');
  }
}

module.exports = config;
