// Generated by CoffeeScript 1.9.1
var compression, config, logger, minify;

logger = require('bragi');

config = require('./config');

compression = require('compression');

minify = require('express-minify');

module.exports = function(app) {
  return app.use(compression()).use(minify({
    cache: config.cache.dir
  })).use(/(\/static)|(\/templates)|(\/$)/, function(req, res, next) {
    logger.log('http:caching', req.url);
    res.header('Cache-Control', "public, max-age=" + config.cache.maxAge);
    return next();
  }).use('/api/v1', function(req, res, next) {
    logger.log('http:no-caching', req.url);
    res.header('Cache-Control', "no-cache, max-age=0");
    return next();
  });
};
