// Generated by CoffeeScript 1.9.1
var bowerFiles, bowerInstall, browserify, config, gulp, inject, nonBowerMainFiles, rename;

gulp = require('gulp');

browserify = require('gulp-browserify');

inject = require('gulp-inject');

rename = require('gulp-rename');

bowerFiles = require('main-bower-files');

bowerInstall = require('gulp-bower');

config = require('./backend/config/config');

gulp.task('bower-install', function() {
  return bowerInstall();
});

gulp.task('bower-copy', ['bower-install'], function() {
  return gulp.src(bowerFiles()).pipe(gulp.dest('frontend/lib'));
});

nonBowerMainFiles = ['./bower_components/ace-builds/src/*'];

gulp.task('non-bower-copy', ['bower-install'], function() {
  return gulp.src(nonBowerMainFiles).pipe(gulp.dest('frontend/lib'));
});

gulp.task('inject-modules', function() {
  return gulp.src('frontend/modules/**/*.js', {
	read: false
  }).pipe(inject('frontend/module-loader.js', {
	starttag: '# start-inject:modules',
	endtag: '# end-inject',
	transform: function(filepath, file, index, length) {
	  filepath = filepath.replace(/^.+?\//, '').replace(/\.coffee/, '');
	  return "require('../" + filepath + "')";
	}
  })).pipe(gulp.dest('frontend/lib/'));
});

gulp.task('move-files', function() {
  var clean;
  clean = require('gulp-clean');
  return gulp.src('frontend/**/*ctrl.coffee').pipe(clean()).pipe(rename(function(path) {
	var basename;
	basename = path.basename.replace(/\-ctrl/, 'Ctrl');
	basename = basename.replace(/.?/, basename[0].toUpperCase());
	path.basename = basename;
	return void 0;
  })).pipe(gulp.dest('frontend'));
});

gulp.task('browserify-sdk', function() {
  return gulp.src('./backend/sdk/init.coffee', {
	read: false
  }).pipe(browserify({
	debug: config.browserify.debug,
	transform: ['coffeeify'],
	extensions: ['.coffee']
  })).pipe(rename('meanads-sdk.js')).pipe(gulp.dest('./frontend/lib'));
});

gulp.task('browserify-client', function() {
  return gulp.src('./frontend/app-bootstrap.coffee', {
	read: false
  }).pipe(browserify({
	debug: config.browserify.debug,
	transform: ['coffeeify'],
	extensions: ['.coffee']
  })).pipe(rename('meanads-client.js')).pipe(gulp.dest('./frontend/lib'));
});

gulp.task('watch', function() {
  gulp.watch(['frontend/modules/**/*.coffee', 'frontend/**.coffee'], ['inject-modules', 'browserify-client']);
  gulp.watch('backend/sdk/*.coffee', ['browserify-sdk']);
  return gulp.watch('bower.json', ['setup-assets']);
});

gulp.task('setup-assets', ['inject-modules', 'browserify-sdk', 'browserify-client']);
