// Generated by CoffeeScript 1.9.1
var NavbarCtrl, app, injected;

app = require('../../app');

injected = 0;

NavbarCtrl = (function() {
  function NavbarCtrl($location) {
    injected = {
      $location: $location
    };
    this.modules = [
      {
        name: "Subscriptions",
        path: "/subscriptions"
      }, {
        name: "Campaigns",
        path: "/campaigns"
      }, {
        name: "Programs",
        path: "/programs"
      }, {
        name: "Styles",
        path: "/styles"
      }
    ].reverse();
  }

  NavbarCtrl.prototype.isActive = function(route) {
    return injected.$location.path().match(route);
  };

  return NavbarCtrl;

})();

NavbarCtrl.$inject = ['$location'];

app.controller('NavListCtrl', NavbarCtrl);
