// Generated by CoffeeScript 1.9.1
var MeanError;

MeanError = require('./modules/MeanError');

module.exports = function() {
  return {
    dateSplit: function(date) {
      return [date.getFullYear(), date.getMonth(), date.getDate()];
    },
    camelCaseToSnakeCase: function(str) {
      var i, k, len, out, v;
      out = "";
      for (k = i = 0, len = str.length; i < len; k = ++i) {
        v = str[k];
        if (v.toUpperCase() === v && k !== 0) {
          out += '-';
        }
        out += v.toLowerCase();
      }
      return out;
    },
    snakeCaseToCamelCase: function(str, separator) {
      var capitalize, i, len, out, v;
      if (separator == null) {
        separator = '-';
      }
      out = "";
      capitalize = true;
      for (i = 0, len = str.length; i < len; i++) {
        v = str[i];
        if (v === separator) {
          capitalize = true;
        } else if (capitalize === true) {
          out += v.toUpperCase();
          capitalize = false;
        } else {
          out += v;
        }
      }
      return out;
    },
    getType: function(item) {
      var x;
      if (item === null) {
        return 'null';
      }
      if (item === void 0) {
        return 'undefined';
      }
      x = {};
      return x.toString.call(item).replace(/\[object /, '').replace(']', '');
    }
  };
};
