// Generated by CoffeeScript 1.9.1
var LoginCtrl, app,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

app = require('../../app');

LoginCtrl = (function() {
  function LoginCtrl(auth, location, store) {
    this.auth = auth;
    this.location = location;
    this.store = store;
    this.onSuccess = bind(this.onSuccess, this);
    if (this.auth.isAuthenticated === true) {
      return this.onSuccess();
    }
    this.auth.signin({}, this.onSuccess);
  }

  LoginCtrl.prototype.onSuccess = function(profile, token) {
    this.store.set('profile', profile);
    this.store.set('token', token);
    return this.location.path('/');
  };

  LoginCtrl.prototype.onError = function(err) {
    throw err;
  };

  return LoginCtrl;

})();

LoginCtrl.$inject = ['auth', '$location', 'store'];

app.controller('LoginCtrl', LoginCtrl);
