// Generated by CoffeeScript 1.9.1
var CampaignAlterCtrl, app;

app = require('../../app');

CampaignAlterCtrl = (function() {
  function CampaignAlterCtrl(rest, alter, tok) {
    this.rest = rest;
    this.alter = alter;
    this.tok = tok;
    this.alter.bootstrap(this, 'campaign');
    this.rest.all('programs').getList().then((function(_this) {
      return function(programs) {
        _this.programs = programs;
      };
    })(this));
  }

  CampaignAlterCtrl.prototype.beforeSave = function() {
    return this.campaign.keywords = this.tok.tokenize(this.campaign.keywords);
  };

  CampaignAlterCtrl.prototype.addKeyword = function() {
    if (!this.campaign.keywordPricing) {
      this.campaign.keywordPricing = [];
    }
    if (this.keyName && this.keyPrice) {
      this.campaign.keywordPricing.push({
        keyName: this.keyName,
        keyPrice: this.keyPrice
      });
    }
    return this.keyName = this.keyPrice = null;
  };

  CampaignAlterCtrl.prototype.removeKeyword = function(keyword) {
    return _.remove(this.campaign.keywordPricing, function(s) {
      return s === keyword;
    });
  };

  return CampaignAlterCtrl;

})();

CampaignAlterCtrl.$inject = ["Restangular", 'AlterControllerExtensionService', 'TokenizerService'];

app.controller('CampaignAlterCtrl', CampaignAlterCtrl);
