// Generated by CoffeeScript 1.9.1
var CampaignCtrl, app,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

app = require('../../app');

CampaignCtrl = (function() {
  function CampaignCtrl(rest) {
    this.rest = rest;
    this._getCampaigns = bind(this._getCampaigns, this);
    this._getCampaigns();
  }

  CampaignCtrl.prototype._getCampaigns = function() {
    return this.rest.all('campaigns').getList({
      populate: 'program'
    }).then((function(_this) {
      return function(campaigns) {
        _this.campaigns = campaigns;
      };
    })(this));
  };

  CampaignCtrl.prototype.toggleStatus = function(campaign) {
    return this.rest.one('campaign', campaign._id).patch({
      isEnabled: !!!campaign.isEnabled
    }).then(this._getCampaigns);
  };

  return CampaignCtrl;

})();

CampaignCtrl.$inject = ['Restangular'];

app.controller('CampaignListCtrl', CampaignCtrl);
