// Generated by CoffeeScript 1.9.1
var CampaignMetricsCtrl, app;

app = require('../../app');

CampaignMetricsCtrl = (function() {
  function CampaignMetricsCtrl(rest, route, $q) {
    var rSubscriptions;
    this.rest = rest;
    this.route = route;
    rSubscriptions = this.rest.all('subscriptions');
    $q.all([
      rSubscriptions.one('count').get({
        campaign: this.route.id
      }), rSubscriptions.one('credits').get({
        campaign: this.route.id
      }), this.rest.one('campaign', this.route.id).get()
    ]).then((function(_this) {
      return function(args) {
        var count;
        count = args[0], _this.credits = args[1], _this.campaign = args[2];
        return _this.subscriptionCount = count.count;
      };
    })(this)).then((function(_this) {
      return function() {
        return _this.rest.one('program', _this.campaign.program).get();
      };
    })(this)).then((function(_this) {
      return function(program) {
        var ref;
        _this.program = program;
        ref = _this.credits, _this.creditDistribution = ref.creditDistribution, _this.creditUsage = ref.creditUsage;
        _this.avgCommitment = Math.round(_this.campaign.commitment / _this.campaign.days);
        _this.creditDistribution = Math.round(_this.creditDistribution / _this.campaign.days);
        _this.creditUsage = Math.round(_this.creditUsage / _this.campaign.days);
        return _this.fulfillment = 100 * _this.creditDistribution / _this.avgCommitment;
      };
    })(this));
  }

  return CampaignMetricsCtrl;

})();

CampaignMetricsCtrl.$inject = ['Restangular', '$routeParams', '$q'];

app.controller('CampaignMetricsCtrl', CampaignMetricsCtrl);
