// Generated by CoffeeScript 1.9.1
var ProfileListCtrl, app;

app = require('../../app');

ProfileListCtrl = (function() {
  function ProfileListCtrl(auth, scope, profile) {
    profile.getProfileQ().then((function(_this) {
      return function(profile1) {
        _this.profile = profile1;
        return _this.profile.picture = _this._reducePicture(_this.profile.picture);
      };
    })(this));
  }

  ProfileListCtrl.prototype._reducePicture = function(picture) {
    return picture.replace('s=480', "s=64");
  };

  return ProfileListCtrl;

})();

ProfileListCtrl.$inject = ['auth', '$scope', 'ProfileService'];

app.controller('ProfileListCtrl', ProfileListCtrl);
