// Generated by CoffeeScript 1.9.1
var ProgramAlterCtrl, app;

app = require('../../app');

ProgramAlterCtrl = (function() {
  function ProgramAlterCtrl(rest, alter, tok) {
    this.rest = rest;
    this.alter = alter;
    this.tok = tok;
    this.alter.bootstrap(this, 'program');
    this.rest.all('styles').getList().then((function(_this) {
      return function(styles) {
        _this.styles = styles;
      };
    })(this));
  }

  ProgramAlterCtrl.prototype.beforeSave = function() {
    return this.program.allowedOrigins = this.tok.tokenize(this.program.allowedOrigins);
  };

  return ProgramAlterCtrl;

})();

ProgramAlterCtrl.$inject = ["Restangular", 'AlterControllerExtensionService', 'TokenizerService'];

app.controller('ProgramAlterCtrl', ProgramAlterCtrl);
