// Generated by CoffeeScript 1.9.1
var ProgramCtrl, app;

app = require('../../app');

ProgramCtrl = (function() {
  function ProgramCtrl(rest) {
    rest.all('programs').getList({
      populate: ['style']
    }).then((function(_this) {
      return function(programs) {
        _this.programs = programs;
      };
    })(this));
  }

  return ProgramCtrl;

})();

ProgramCtrl.$inject = ["Restangular"];

app.controller('ProgramListCtrl', ProgramCtrl);
