// Generated by CoffeeScript 1.9.1
var StyleCtrl, app;

app = require('../../app');

StyleCtrl = (function() {
  function StyleCtrl(rest) {
    rest.all('styles').getList().then((function(_this) {
      return function(styles) {
        _this.styles = styles;
      };
    })(this));
  }

  return StyleCtrl;

})();

StyleCtrl.$inject = ['Restangular'];

app.controller('StyleListCtrl', StyleCtrl);
