// Generated by CoffeeScript 1.9.1
var DispatchSchema;

DispatchSchema = function(mongoose) {
  return new mongoose.Schema({
    markup: {
      type: String,
      required: true
    },
    subscription: {
      type: mongoose.Schema.ObjectId,
      required: true,
      ref: 'Subscription',
      index: true
    },
    allowedOrigins: {
      type: [String]
    },
    program: {
      type: mongoose.Schema.ObjectId,
      required: true,
      ref: 'Program',
      index: true
    },
    lastDeliveredOn: {
      type: Date,
      "default": Date.now
    },
    startDate: {
      type: Date,
      required: true
    },
    keywords: {
      type: [String],
      index: true
    },
    data: {
      type: mongoose.Schema.Types.Mixed
    }
  });
};

module.exports = DispatchSchema;
