// Generated by CoffeeScript 1.9.1
var GlobProvider, GlobProviderMock, Provide, _;

Provide = require('di').Provide;

_ = require('lodash');

GlobProvider = require('../../backend/providers/GlobProvider');

GlobProviderMock = (function() {
  function GlobProviderMock() {}

  GlobProviderMock.prototype.glob = function() {};

  return GlobProviderMock;

})();

GlobProviderMock.annotations = [new Provide(GlobProvider)];

module.exports = GlobProviderMock;
