// Generated by CoffeeScript 1.9.1
var HttpProvider, HttpProviderMock, Provide, annotate, ref,
  slice = [].slice;

HttpProvider = require('../../backend/sdk/HttpProvider');

ref = require('di'), annotate = ref.annotate, Provide = ref.Provide;

HttpProviderMock = (function() {
  function HttpProviderMock() {}

  HttpProviderMock.prototype.get = function(url, options, callback) {
    this.callback = callback;
  };

  HttpProviderMock.prototype.$flush = function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    if (!this.callback) {
      throw Error('Set the callback dude!');
    }
    return this.callback.apply(this, args);
  };

  return HttpProviderMock;

})();

annotate(HttpProviderMock, new Provide(HttpProvider));

module.exports = HttpProviderMock;
