// Generated by CoffeeScript 1.9.1
var f, files, glob;

glob = require('glob');

files = glob('*Mock.coffee', {
  sync: true,
  cwd: './test/mocks'
});

module.exports = (function() {
  var i, len, results;
  results = [];
  for (i = 0, len = files.length; i < len; i++) {
    f = files[i];
    results.push(require("./" + f));
  }
  return results;
})();
