// Generated by CoffeeScript 1.9.1
var MailgunProvider, MailgunProviderMock, Provide, Q, annotate, ref;

ref = require('di'), Provide = ref.Provide, annotate = ref.annotate;

Q = require('q');

MailgunProvider = require('../../backend/providers/MailgunProvider');

MailgunProviderMock = (function() {
  function MailgunProviderMock() {
    sinon.spy(this, 'sendMessageQ');
  }

  MailgunProviderMock.prototype.sendMessageQ = function() {
    return Q('sent-mailgun-request');
  };

  return MailgunProviderMock;

})();

annotate(MailgunProviderMock, new Provide(MailgunProvider));

module.exports = MailgunProviderMock;
