// Generated by CoffeeScript 1.9.1
var Q, _, campaign, dispatches, ownerId, program, style, subscription, subscription2, subscription3, subscription4;

Q = require('q');

_ = require('lodash');

ownerId = 9000;

campaign = {
  name: 'apple-campaign',
  days: 10,
  owner: ownerId,
  defaultCost: 1,
  isEnabled: true
};

subscription = {
  client: 'apples',
  totalCredits: 1000,
  keywords: ["abc"],
  usedCredits: 120,
  data: {
    a: 'aaa',
    b: 'bbb',
    c: 'ccc'
  },
  owner: ownerId,
  emailAccess: ['a@a.com', 'b@b.com', 'c@c.com'],
  keywords: ['inky', 'pinky', 'ponky'],
  impressions: 1000
};

subscription2 = {
  client: 'apples2',
  totalCredits: 2000,
  keywords: ["abc"],
  usedCredits: 120,
  data: {
    a: 'aaa2',
    b: 'bbb2',
    c: 'ccc2'
  },
  owner: ownerId
};

subscription3 = {
  client: 'apples3',
  totalCredits: 3000,
  keywords: ["abc"],
  usedCredits: 120,
  data: {
    a: 'aaa3',
    b: 'bbb3',
    c: 'ccc3'
  },
  owner: 9001
};

subscription4 = {
  client: 'apples4',
  totalCredits: 4000,
  keywords: ["abc"],
  usedCredits: 120,
  data: {
    a: 'aaa4',
    b: 'bbb4',
    c: 'ccc4'
  },
  owner: ownerId
};

dispatches = [
  {
    markup: 'hello world 1',
    startDate: new Date(2014, 1, 1),
    keywords: ['aa', 'bb']
  }, {
    markup: 'hello world 2 ',
    startDate: new Date(2014, 1, 1),
    keywords: ['bb', 'cc']
  }, {
    markup: 'hello world 3',
    startDate: new Date(2014, 1, 1),
    keywords: ['cc', 'dd']
  }
];

program = {
  name: 'apple-program',
  owner: ownerId
};

style = {
  name: 'apple-style',
  html: '<div>{{=it.a}}</div><h2 href="{{=it.c}}">{{=it.b}}</h2>',
  css: 'p {position: absolute;}   a.selected {color: #f3a;}',
  placeholders: ['a', 'b', 'c'],
  owner: ownerId
};

exports.mockDataSetup = function() {
  return new this.Models.Style(style).saveQ().then((function(_this) {
    return function(style1) {
      _this.style = style1;
      program.style = _this.style._id;
      return new _this.Models.Program(program).saveQ();
    };
  })(this)).then((function(_this) {
    return function(program1) {
      _this.program = program1;
      campaign.program = _this.program._id;
      return new _this.Models.Campaign(campaign).saveQ();
    };
  })(this)).then((function(_this) {
    return function(campaign1) {
      _this.campaign = campaign1;
      subscription.campaign = _this.campaign._id;
      subscription2.campaign = _this.campaign._id;
      subscription3.campaign = _this.campaign._id;
      subscription4.campaign = _this.campaign._id;
      return Q.all([new _this.Models.Subscription(subscription).saveQ(), new _this.Models.Subscription(subscription2).saveQ(), new _this.Models.Subscription(subscription3).saveQ(), new _this.Models.Subscription(subscription4).saveQ()]);
    };
  })(this)).spread((function(_this) {
    return function(subscription1) {
      _this.subscription = subscription1;
      return Q.all(_.map(dispatches, function(d) {
        d.subscription = _this.subscription._id;
        d.program = _this.program._id;
        return new _this.Models.Dispatch(d).saveQ();
      }));
    };
  })(this)).spread((function(_this) {
    return function(dispatch) {
      _this.dispatch = dispatch;
    };
  })(this));
};
