// Generated by CoffeeScript 1.9.1
var MongooseProvider, MongooseProviderMock, Provide, mockgoose, mongoose, mongooseQ;

Provide = require('di').Provide;

mockgoose = require('mockgoose');

mongooseQ = require('mongoose-q');

mongoose = require('mongoose');

MongooseProvider = require('../../backend/providers/MongooseProvider');

MongooseProviderMock = (function() {
  function MongooseProviderMock() {
    this.mongoose = mongooseQ(mockgoose(mongoose));
  }

  MongooseProviderMock.prototype.__reset = function() {
    this.mongoose.models = {};
    return mockgoose.reset();
  };

  MongooseProviderMock.prototype.__fakeModel = function(schema, modelName) {
    var FakeSchema;
    if (schema == null) {
      schema = {};
    }
    if (modelName == null) {
      modelName = 'FakeModel';
    }
    FakeSchema = this.mongoose.Schema(schema);
    return this.mongoose.model(modelName, FakeSchema);
  };

  return MongooseProviderMock;

})();

MongooseProviderMock.annotations = [new Provide(MongooseProvider)];

module.exports = MongooseProviderMock;
