// Generated by CoffeeScript 1.9.1
var Provide, Q, RedisConnection, RedisConnectionMock, annotate, ref;

RedisConnection = require('../../backend/connections/RedisConnection');

Q = require('q');

ref = require('di'), annotate = ref.annotate, Provide = ref.Provide;

RedisConnectionMock = (function() {
  function RedisConnectionMock() {
    this.conn = {
      memory: {},
      set: function(key, val) {
        return this.memory[key] = val;
      },
      get: function(key) {
        return Q(this.memory[key].toString());
      },
      incrby: function(key, val) {
        if (!this.memory[key]) {
          this.memory[key] = 0;
        }
        return this.memory[key] += val;
      },
      incr: function(key) {
        return this.incrby(key, 1);
      }
    };
  }

  return RedisConnectionMock;

})();

annotate(RedisConnectionMock, new Provide(RedisConnection));

module.exports = RedisConnectionMock;
