// Generated by CoffeeScript 1.9.1
var Provide, RequireProvider, RequireProviderMock;

Provide = require('di').Provide;

RequireProvider = require('../../backend/providers/RequireProvider');

RequireProviderMock = (function() {
  function RequireProviderMock() {}

  RequireProviderMock.prototype.require = sinon.spy(function(name) {
    return name + "-required";
  });

  return RequireProviderMock;

})();

RequireProviderMock.annotations = [new Provide(RequireProvider)];

module.exports = RequireProviderMock;
