// Generated by CoffeeScript 1.9.1
var ClassProvider, CommandExecutor, annotate, ref;

ref = require('di'), annotate = ref.annotate, ClassProvider = ref.ClassProvider;

CommandExecutor = (function() {
  function CommandExecutor() {
    this._executables = {};
  }

  CommandExecutor.prototype.register = function(cmd) {
    if (!cmd.alias) {
      throw new Error('Alias not found dude!');
    }
    return this._executables[cmd.alias] = cmd;
  };

  CommandExecutor.prototype.execute = function(alias, args) {
    var ref1;
    return (ref1 = this._executables[alias]) != null ? typeof ref1.execute === "function" ? ref1.execute.apply(ref1, args) : void 0 : void 0;
  };

  return CommandExecutor;

})();

annotate(CommandExecutor, new ClassProvider());

module.exports = CommandExecutor;
