// Generated by CoffeeScript 1.9.1
var ClassProvider, CreateImageElement, Inject, WindowProvider, annotate, ref;

WindowProvider = require('../providers/WindowProvider');

ref = require('di'), annotate = ref.annotate, Inject = ref.Inject, ClassProvider = ref.ClassProvider;

CreateImageElement = (function() {
  function CreateImageElement(windowP) {
    this.windowP = windowP;
  }

  CreateImageElement.prototype.create = function(url, callback) {
    var document, img;
    document = this.windowP.window().document;
    img = document.createElement('img');
    img.src = url;
    return img.onload = img.onerror = function() {
      img.onload = img.onerror = null;
      if (callback) {
        return callback();
      }
    };
  };

  return CreateImageElement;

})();

annotate(CreateImageElement, new ClassProvider);

annotate(CreateImageElement, new Inject(WindowProvider));

module.exports = CreateImageElement;
