// Generated by CoffeeScript 1.9.1
var ClassProvider, HttpProvider, annotate, ref;

ref = require('di'), ClassProvider = ref.ClassProvider, annotate = ref.annotate;

HttpProvider = (function() {
  function HttpProvider() {
    this.ajax = require('component-ajax');
  }

  HttpProvider.prototype.get = function(url, xhrFields, success) {
    return this.ajax({
      url: url,
      xhrFields: xhrFields,
      success: success
    });
  };

  return HttpProvider;

})();

annotate(HttpProvider, new ClassProvider);

module.exports = HttpProvider;
