// Generated by CoffeeScript 1.9.1
var Injector, Main, injector, main;

Injector = require('di').Injector;

Main = require('./Main');

injector = new Injector();

main = injector.get(Main);

main.setup();
