// Generated by CoffeeScript 1.9.1
var Inject, JadeProvider, JuiceProvider, Mailer, MailgunProvider, annotate, humanize, ref;

JadeProvider = require('../providers/JadeProvider');

JuiceProvider = require('../providers/JuiceProvider');

MailgunProvider = require('../providers/MailgunProvider');

ref = require('di'), Inject = ref.Inject, annotate = ref.annotate;

humanize = require('humanize');

Mailer = (function() {
  function Mailer(jade, juice, mail) {
    this.jade = jade;
    this.juice = juice;
    this.mail = mail;
  }

  Mailer.prototype.getTemplatePath = function(name) {
    return "./frontend/templates/mailers/" + name + "-tmpl.jade";
  };

  Mailer.prototype.interpolate = function(jadeTemplate, locals) {
    var templateFn, templatePath;
    templatePath = this.getTemplatePath(jadeTemplate);
    templateFn = this.jade.compileFile(templatePath);
    return templateFn(locals);
  };

  Mailer.prototype.sendQ = function(options) {
    var from, locals, markup, subject, template, to;
    from = options.from, to = options.to, subject = options.subject, template = options.template, locals = options.locals;
    locals.humanize = humanize;
    markup = this.interpolate(template, locals);
    return this.juice.juiceContentQ(markup).then((function(_this) {
      return function(inlineMarkup) {
        return _this.mail.sendMessageQ(from, to, subject, inlineMarkup);
      };
    })(this));
  };

  return Mailer;

})();

annotate(Mailer, new Inject(JadeProvider, JuiceProvider, MailgunProvider));

module.exports = Mailer;
