// Generated by CoffeeScript 1.9.1
var MeanError,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

MeanError = (function(superClass) {
  extend(MeanError, superClass);

  function MeanError(message, code, httpStatus) {
    this.message = message;
    this.code = code != null ? code : 'KNOWN_ERROR';
    this.httpStatus = httpStatus != null ? httpStatus : '500';
    this.type = 'mean';
  }

  return MeanError;

})(Error);

module.exports = MeanError;
