// Generated by CoffeeScript 1.9.1
var Inject, ModelFactory, Q, SubscriptionPopulator, _, annotate, less, ref;

ModelFactory = require('../factories/ModelFactory');

Q = require('q');

less = require('less');

_ = require('lodash');

ref = require('di'), annotate = ref.annotate, Inject = ref.Inject;

SubscriptionPopulator = (function() {
  function SubscriptionPopulator(models) {
    this.models = models;
  }

  SubscriptionPopulator.prototype._getModel = function(name) {
    return this.models[name];
  };

  SubscriptionPopulator.prototype.populateSubscription = function(subscriptionId) {
    var _subscription;
    _subscription = {};
    return this._getModel('Subscription').findOne({
      _id: subscriptionId
    }).populate('campaign').execQ().then(function(subscription) {
      if (!subscription) {
        return null;
      }
      _subscription = subscription;
      return subscription.campaign.populateQ('program').then(function(campaign) {
        _subscription.campaign = campaign;
        return campaign.program.populateQ('style');
      }).then(function(program) {
        _subscription.campaign.program = program;
        return _subscription;
      });
    });
  };

  return SubscriptionPopulator;

})();

annotate(SubscriptionPopulator, new Inject(ModelFactory));

module.exports = SubscriptionPopulator;
