// Generated by CoffeeScript 1.9.1
var ControllerFactory, ControllerNames, Inject, Injector, _, annotate, ref, resources;

ref = require('di'), Inject = ref.Inject, Injector = ref.Injector, annotate = ref.annotate;

resources = require('../config/config').resources;

ControllerNames = ['Campaign', 'Dispatch', 'Experiment', 'Program', 'Style', 'Subscription'];

_ = require('lodash');

ControllerFactory = (function() {
  function ControllerFactory(injector) {
    this.Controllers = {};
    _.each(ControllerNames, (function(_this) {
      return function(i) {
        return _this.Controllers[i] = injector.get(require("../controllers/" + i + "Controller"));
      };
    })(this));
  }

  return ControllerFactory;

})();

annotate(ControllerFactory, new Inject(Injector));

module.exports = ControllerFactory;
