// Generated by CoffeeScript 1.9.1
var DateProvider;

DateProvider = (function() {
  function DateProvider() {}

  DateProvider.prototype.now = function() {
    return new Date(Date.now());
  };

  return DateProvider;

})();

module.exports = DateProvider;
