// Generated by CoffeeScript 1.9.1
var DotProvider, dot;

dot = require('dot');

DotProvider = (function() {
  function DotProvider() {
    dot.templateSettings.strip = true;
  }

  DotProvider.prototype.template = function(html) {
    return dot.template(html);
  };

  return DotProvider;

})();

module.exports = DotProvider;
