// Generated by CoffeeScript 1.9.1
var GlobProvider, glob;

glob = require('glob');

GlobProvider = (function() {
  function GlobProvider() {}

  GlobProvider.prototype.glob = glob;

  return GlobProvider;

})();

module.exports = GlobProvider;
