// Generated by CoffeeScript 1.9.1
var JadeProvider, jade;

jade = require('jade');

JadeProvider = (function() {
  function JadeProvider() {
    this.options = {};
  }

  JadeProvider.prototype.compileFile = function(source) {
    return jade.compileFile(source, this.options);
  };

  return JadeProvider;

})();

module.exports = JadeProvider;
