// Generated by CoffeeScript 1.9.1
var MailgunProvider, apiKey, domain, mailgun, ref;

ref = require('../config/config').mailgun, apiKey = ref.apiKey, domain = ref.domain;

mailgun = require('mailgun-js');

MailgunProvider = (function() {
  function MailgunProvider() {
    this.mailgun = mailgun({
      apiKey: apiKey,
      domain: domain
    });
  }

  MailgunProvider.prototype.sendMessageQ = function(from, to, subject, html) {
    return this.mailgun.messages().send({
      from: from,
      to: to,
      subject: subject,
      html: html
    });
  };

  return MailgunProvider;

})();

module.exports = MailgunProvider;
