// Generated by CoffeeScript 1.9.1
var MongooseProvider;

MongooseProvider = (function() {
  function MongooseProvider() {
    this.mongoose = require('mongoose-q')(require('mongoose'));
  }

  return MongooseProvider;

})();

module.exports = MongooseProvider;
