// Generated by CoffeeScript 1.9.1
var Redis;

Redis = (function() {
  function Redis() {}

  Redis.prototype.redis = function() {
    return require('then-redis');
  };

  return Redis;

})();

module.exports = Redis;
