// Generated by CoffeeScript 1.9.1
var RequireProvider;

RequireProvider = (function() {
  function RequireProvider() {}

  RequireProvider.prototype.require = require;

  return RequireProvider;

})();

module.exports = RequireProvider;
