// Generated by CoffeeScript 1.9.1
var ClassProvider, WindowProvider, annotate, ref;

ref = require('di'), ClassProvider = ref.ClassProvider, annotate = ref.annotate;

WindowProvider = (function() {
  function WindowProvider() {}

  WindowProvider.prototype.window = function() {
    return window;
  };

  return WindowProvider;

})();

annotate(WindowProvider, new ClassProvider);

module.exports = WindowProvider;
