// Generated by CoffeeScript 1.9.1
var ProfileService, app;

app = require('./app');

ProfileService = (function() {
  function ProfileService(auth, Q, store, rootScope) {
    this.auth = auth;
    this.Q = Q;
    this.store = store;
    this.rootScope = rootScope;
  }

  ProfileService.prototype.getProfileQ = function() {
    var profile, token;
    profile = this.store.get('profile');
    if (profile) {
      return this.Q(function(r) {
        return r(profile);
      });
    }
    token = this.store.get('token');
    if (!token) {
      return this.rootscope.$broadcast('unauthenticated');
    }
    return this.auth.getProfile(token).then((function(_this) {
      return function(profile) {
        _this.store.set('profile', profile);
        return profile;
      };
    })(this));
  };

  return ProfileService;

})();

ProfileService.$inject = ['auth', '$q', 'store', '$rootScope'];

app.service('ProfileService', ProfileService);
