// Generated by CoffeeScript 1.9.1
var MeanLoader, app;

app = require('../../app');

MeanLoader = function(pendingRequests) {
  var el, onCountChange;
  el = {};
  onCountChange = function(count) {
    if (count === 0) {
      return el.css('display', 'none');
    } else {
      return el.css('display', 'block');
    }
  };
  pendingRequests.onCountChange(onCountChange);
  return {
    link: function(scope, element, attrs) {
      return el = element;
    }
  };
};

app.directive('meanLoader', ['AjaxPendingRequests', MeanLoader]);
