// Generated by CoffeeScript 1.9.1
var app;

app = require('../../app');

app.directive('meanShadowDom', function() {
  return {
    scope: {
      html: '=meanShadowDom'
    },
    link: function(scope, element, attrs) {
      var createShadowRoot, shadowElement;
      createShadowRoot = element[0].createShadowRoot || element[0].webkitCreateShadowRoot;
      shadowElement = createShadowRoot.call(element[0]);
      return scope.$watch('html', function() {
        if (scope.html) {
          return shadowElement.innerHTML = scope.html;
        }
      });
    }
  };
});
